version: "3.7"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turret_prod
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      DATABASE_URL: postgres://postgres:postgres@db/turret_prod
    env_file:
      - .env

  caddy:
    image: caddy:latest
    restart: always
    volumes:
      - ./priv/cert:/root/certs
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 4000:4000
    depends_on:
      - web

volumes:
  pgdata:
